name: Build search data and create release on new tag

# Controls when the action will run. Triggers the workflow on new tags
on:
  push:
    tags:
      - 'v2.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-commit-search-data:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Install AutoHotkey v2 32-bit
      run: |
        choco install autohotkey.portable --pre --x86

    - name: Run build_search.ahk
      run: |
        Start-Process -FilePath "AutoHotkey.exe" -ArgumentList "/ErrorStdOut `"static/source/build_search.ahk`"" -NoNewWindow -Wait

    - name: Commit
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git commit -a -m "Build data_search.js"
        git push
